Switch to zserio 2.4.2
Klebert-Engineering/zsomeip pull request #6
Opened 2022-03-24 16:07 UTC by l-laura

Since current services are mainly zserio 2.4.2 compatible, I changed zsomeip to use it by default. The flag is documented in README and I tested the weather service using both zserio versions.

2022-03-25 15:58 UTC, josephbirkner requested changes
Looks good, but I have a small change request for how a user can switch the used version...

2022-03-25 15:58 UTC, josephbirkner commented on client-service/ZsomeIpService.cpp
> +        uint32_t length = response_payload_->get_length();
Consider `auto`? (also above?)

2022-03-25 15:58 UTC, josephbirkner commented on client-service/ZsomeIpService.h
> +            : public ZsomeIpApp, public zserio::IService {
Consider to align indentation usages of `#if` and `#else` blocks

2022-04-01 04:48 UTC, l-laura commented on CMakeLists.txt
> +add_compile_definitions(ZSERIO_2_4_2_SERVICE_INTERFACE)
That's a good idea - the change is in, although I renamed the option to ``ZSOMEIP_USE_2_5_0_ZSERIO_SERVICE_INTERFACE`` for clarity. Also updated documentation on the option.

2022-04-01 04:54 UTC, merged